/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestField {
    }
    interface TestInput {
        "placeholder"?: string;
    }
    interface TestLabel {
    }
}
declare global {
    interface HTMLTestFieldElement extends Components.TestField, HTMLStencilElement {
    }
    var HTMLTestFieldElement: {
        prototype: HTMLTestFieldElement;
        new (): HTMLTestFieldElement;
    };
    interface HTMLTestInputElement extends Components.TestInput, HTMLStencilElement {
    }
    var HTMLTestInputElement: {
        prototype: HTMLTestInputElement;
        new (): HTMLTestInputElement;
    };
    interface HTMLTestLabelElement extends Components.TestLabel, HTMLStencilElement {
    }
    var HTMLTestLabelElement: {
        prototype: HTMLTestLabelElement;
        new (): HTMLTestLabelElement;
    };
    interface HTMLElementTagNameMap {
        "test-field": HTMLTestFieldElement;
        "test-input": HTMLTestInputElement;
        "test-label": HTMLTestLabelElement;
    }
}
declare namespace LocalJSX {
    interface TestField {
    }
    interface TestInput {
        "placeholder"?: string;
    }
    interface TestLabel {
    }
    interface IntrinsicElements {
        "test-field": TestField;
        "test-input": TestInput;
        "test-label": TestLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-field": LocalJSX.TestField & JSXBase.HTMLAttributes<HTMLTestFieldElement>;
            "test-input": LocalJSX.TestInput & JSXBase.HTMLAttributes<HTMLTestInputElement>;
            "test-label": LocalJSX.TestLabel & JSXBase.HTMLAttributes<HTMLTestLabelElement>;
        }
    }
}
